<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>83a4c5af-0326-415b-8c0e-9d874a8aa74d</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.11">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="GestionEstudiantes.SeleniumTests/**/*.cs" />
    <Content Remove="GestionEstudiantes.SeleniumTests/**" />
    <EmbeddedResource Remove="GestionEstudiantes.SeleniumTests/**" />
    <None Remove="GestionEstudiantes.SeleniumTests/**" />
  </ItemGroup>

</Project>
